name: 🚀 NPM Publish

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          bun-version: latest
          registry-url: https://npm.pkg.github.com/
      - run: bun install
      - run: bun run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.JOHZAO_TOKEN}}
